# SPDX-FileCopyrightText: 2022 Emisse
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Paul Ritter
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Sailor
# SPDX-FileCopyrightText: 2023 potato1234_x
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2025 DeusMaldPr
# SPDX-FileCopyrightText: 2025 Minemoder5000
# SPDX-FileCopyrightText: 2025 War Pigeon
# SPDX-FileCopyrightText: 2025 beck-thompson
#
# SPDX-License-Identifier: MPL-2.0

- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 10800 #3 hrs, klovn
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: AtmosphericTechnicianChameleonOutfit
  job: AtmosphericTechnician
  equipment:
    head: ClothingHeadHelmetAtmosFire
    mask: ClothingMaskGasAtmos
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterSuitAtmosFire
    gloves: ClothingHandsGlovesColorYellow
