# SPDX-FileCopyrightText: 2020 Peter Wedder
# SPDX-FileCopyrightText: 2021 20kdc
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2021 wrexbe
# SPDX-FileCopyrightText: 2022 Flareguy
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Lamrr
# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Emisse
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 crazybrain23
# SPDX-FileCopyrightText: 2023 nmajask
# SPDX-FileCopyrightText: 2023 randy10122
# SPDX-FileCopyrightText: 2024 Brandon Hu
# SPDX-FileCopyrightText: 2024 Ed
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Myra
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2024 Repo
# SPDX-FileCopyrightText: 2024 Theodore Lukin
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2025 DeusMaldPr
# SPDX-FileCopyrightText: 2025 Hitlinemoss
# SPDX-FileCopyrightText: 2025 Minemoder5000
# SPDX-FileCopyrightText: 2025 beck-thompson
#
# SPDX-License-Identifier: MPL-2.0

- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 9000 #2.5 hrs, klovn
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 9000 #2.5 hrs
#    - !type:DepartmentTimeRequirement, klovn, redundant
#      department: Cargo
#      time: 36000 #10 hours
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboardThreePapers
    pocket1: AppraisalTool
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
  hasMindShield: true
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
