# SPDX-FileCopyrightText: 2022 DrSmugleaf
# SPDX-FileCopyrightText: 2022 EmoGarbage404
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Paul Ritter
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 JoeHammad1844
# SPDX-FileCopyrightText: 2023 Kit0vras
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 Nim
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Whisper
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Hanz
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Nemanja
# SPDX-FileCopyrightText: 2024 Unkn0wn_Gh0st
# SPDX-FileCopyrightText: 2024 Winkarst
# SPDX-FileCopyrightText: 2025 Alpha-Two
# SPDX-FileCopyrightText: 2025 DeusMaldPr
# SPDX-FileCopyrightText: 2025 IProduceWidgets
# SPDX-FileCopyrightText: 2025 ScarKy0
# SPDX-FileCopyrightText: 2025 UpAndLeaves
# SPDX-FileCopyrightText: 2025 beck-thompson
#
# SPDX-License-Identifier: MIT

# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Security
    time: 18000 #5 hrs, klovn
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTLeader
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    neck: Whistle
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
    suitstorage: WeaponDisablerSMG
  storage:
    back:
    - Binoculars
    - HoloprojectorField
    - PhoneInstrument
    - PinpointerNuclear
    - PowerCellHigh
    - PowerCellHigh
    - MedkitCombatFilled # End of first line
    - MedkitCombatFilled
    - TelescopicShield
    belt:
    - Stunbaton
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolN1984
    - MagazineMagnum
    - EmergencyMedipen

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGearArmed
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponRifleLecterXL8
  storage:
    back:
    - HoloprojectorField
    - PhoneInstrument
    - PinpointerNuclear
    - MagazineRifle
    - MagazineRifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium
    - MedkitCombatFilled # End of first line
    - GrenadeShrapnel
    - EmpGrenade
    belt:
    - Truncheon
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolN1984
    - MagazineMagnum
    - EmergencyMedipen

- type: chameleonOutfit
  id: ERTLeaderChameleonOutfit
  job: ERTLeader
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTLeader
    neck: ClothingNeckBronzeheart

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconERTChaplain"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTChaplainGearEVA
  id: ERTChaplainGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatFez
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
  storage:
    back:
    - BoxCandle
    - BodyBagFolded
    - BodyBagFolded
    - JugWater
    - JugBlood # End of first row
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    belt:
    - Bible
    - Lantern
    - Lantern
    - Lantern
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - FlippoEngravedLighter

- type: chameleonOutfit
  id: ERTChaplainChameleonOutfit
  job: ERTChaplain
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTChaplain
    mask: ClothingMaskGasERT
    outerClothing: ClothingOuterHardsuitERTChaplain
    shoes: ClothingShoesBootsMagAdv

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Engineering
    time: 9000 #2.5 hrs
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconERTEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTEngineer
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
  storage:
    back:
    - RCD
    - GasAnalyzer
    - trayScanner
    - HolofanProjector
    - PartRodMetal
    - SheetPlasteel # End of first line
    - MiningDrillDiamond
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - MetalFoamGrenade
    - AirGrenade
    belt:
    - JawsOfLife
    - PowerDrill
    - WelderIndustrialAdvanced
    - Multitool
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGearArmed
  equipment:
    suitstorage: WeaponShotgunEnforcer
  storage:
    back:
    - RCD
    - GasAnalyzer
    - HolofanProjector
    - MiningDrillDiamond
    - BoxLethalshot
    - BoxShotgunSlug # End of first line
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - CableDetStack
    - BoxDetonator

- type: chameleonOutfit
  id: ERTEngineerChameleonOutfit
  job: ERTEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTEngineer
    neck: ClothingNeckEngineermedal

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Security
    time: 3600
  setPreference: false
  startingGear: ERTSecurityGearEVA
  icon: "JobIconERTSecurity"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTSecurity
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    neck: SecurityWhistle
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
    suitstorage: WeaponDisablerSMG
  storage:
    back:
    - BoxZiptie
    - Flash
    - GrenadeFlashBang
    - TearGasGrenade
    - GrenadeStinger
    - MedkitCombatFilled # End of first line
    - TelescopicShield
    - HoloprojectorSecurity
    - PowerCellHigh
    belt:
    - Stunbaton
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: startingGear
  id: ERTSecurityGearArmedRifle
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
    suitstorage: WeaponRifleLecter
  inhand:
    - WeaponLaserCannon
    - PortableRecharger
  storage:
    belt:
    - CrowbarRed
    - Zipties
    - MedkitCombatFilled
    - MagazineRifle
    - MagazineRifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium
    - Zipties

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedGrenade
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponLauncherHydraLethal
  storage:
    back:
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - MagazinePistol
    - MedkitCombatFilled # End of first line
    - GrenadeEMP
    - GrenadeEMP
    - GrenadeEMP
    - GrenadeFlash
    - GrenadeFlash
    - GrenadeFlash
    - MagazinePistol
    belt:
    - Truncheon
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedVanguard
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponSubMachineGunWt550
  storage:
    back:
    - ExGrenade
    - SmokeGrenade
    - EmpGrenade
    - HoloprojectorSecurity
    - TelescopicShield
    - TelescopicShield
    - TelescopicShield
    - MedkitCombatFilled # End of first line
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    belt:
    - Truncheon
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedShotgun
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponShotgunEnforcer
  storage:
    back:
    - SmokeGrenade
    - BoxLethalshot
    - BoxShotgunSlug
    - BoxShotgunIncendiary
    - MedkitCombatFilled # End of first line
    - SmokeGrenade
    - ExGrenade
    - CableDetStack
    - BoxDetonator
    belt:
    - Truncheon
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: chameleonOutfit
  id: ERTSecurityChameleonOutfit
  job: ERTSecurity
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTSecurity
    neck: ClothingNeckSecuritymedal

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Medical
    time: 7200
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconERTMedic"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTMedicalGearEVA
  id: ERTMedicalGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTMedic
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
  storage:
    back:
    - Hypospray
    - BeakerSmallBruiz
    - BeakerSmallLace
    - JugPunctTranex
    - JugPyraDerma
    - JugDexPlusSaline # End of first line
    - JugTrico
    - BeakerSmallArith
    - BeakerSmallDiph
    - BeakerSmallSigy
    - ClothingEyesGlassesChemical
    - ChemistryBottleOmnizine
    belt:
    - DefibrillatorCompact
    - MedkitCombatFilled
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: startingGear
  parent: ERTMedicalGearEVA
  id: ERTMedicalGearArmed
  equipment:
    suitstorage: WeaponRifleLecter
    pocket2: WeaponDisabler
  storage:
    back:
    - Hypospray
    - JugPunctTranex
    - JugPyraDerma
    - JugDexPlusSaline
    - JugTrico # End of first line
    - BeakerSmallArith
    - DefibrillatorCompact
    - MedkitCombatFilled
    - ClothingEyesGlassesChemical
    - ChemistryBottleOmnizine
    belt:
    - Truncheon
    - Zipties
    - CrowbarRed
    - MagazineRifle
    - MagazineRifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium # End of first line
    - Zipties

- type: chameleonOutfit
  id: ERTMedicalChameleonOutfit
  job: ERTMedical
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTMedical
    neck: ClothingNeckStethoscope

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconERTJanitor"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTJanitorGearEVA
  id: ERTJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
    suitstorage: WeaponLauncherHydra
  storage:
    back:
    - TrashBag
    - SoapNT
    - Plunger
    - Screwdriver
    - AdvMopItem # End of first line
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    belt:
    - MegaSprayBottleSpaceCleaner
    - Holoprojector
    - LightReplacer
    - WireBrush
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: chameleonOutfit
  id: ERTJanitorChameleonOutfit
  job: ERTJanitor
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTJanitor
    neck: ClothingNeckScarfStripedPurple
    eyes: ClothingEyesGlassesSunglasses
