# SPDX-FileCopyrightText: 2022 DrSmugleaf
# SPDX-FileCopyrightText: 2022 EmoGarbage404
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Paul Ritter
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 JoeHammad1844
# SPDX-FileCopyrightText: 2023 Kit0vras
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 Nim
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Whisper
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Hanz
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Nemanja
# SPDX-FileCopyrightText: 2024 Unkn0wn_Gh0st
# SPDX-FileCopyrightText: 2024 Winkarst
# SPDX-FileCopyrightText: 2025 Alpha-Two
# SPDX-FileCopyrightText: 2025 DeusMaldPr
# SPDX-FileCopyrightText: 2025 IProduceWidgets
# SPDX-FileCopyrightText: 2025 ScarKy0
# SPDX-FileCopyrightText: 2025 UpAndLeaves
# SPDX-FileCopyrightText: 2025 beck-thompson
#
# SPDX-License-Identifier: MPL-2.0

# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Security
    time: 18000 #5 hrs, klovn
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTLeader
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolN1984
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazineMagnum

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolN1984
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazineMagnum

- type: startingGear
  id: ERTLeaderGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: MagazineRifle
    pocket2: MagazineRifle
  inhand:
  - WeaponRifleLecterXL8
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazineMagnum

- type: chameleonOutfit
  id: ERTLeaderChameleonOutfit
  job: ERTLeader
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTLeader
    neck: ClothingNeckBronzeheart

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesLeather
    head: ClothingHeadHatFez
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: Flare
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: Flare
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter

- type: chameleonOutfit
  id: ERTChaplainChameleonOutfit
  job: ERTChaplain
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTChaplain
    mask: ClothingMaskGasERT
    outerClothing: ClothingOuterHardsuitERTChaplain
    shoes: ClothingShoesBootsMagAdv

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Engineering
    time: 9000 #2.5 hrs
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsWork
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: Flare
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: Flare
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: chameleonOutfit
  id: ERTEngineerChameleonOutfit
  job: ERTEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTEngineer
    neck: ClothingNeckEngineermedal

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Security
    time: 3600
  setPreference: false
  startingGear: ERTSecurityGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazinePistol

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazinePistol

- type: startingGear
  id: ERTSecurityGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: MagazineRifle
    pocket2: MagazineRifle
  inhand:
    - WeaponRifleLecter
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazinePistol

- type: chameleonOutfit
  id: ERTSecurityChameleonOutfit
  job: ERTSecurity
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTSecurity
    neck: ClothingNeckSecuritymedal

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  requirements:
  - !type:DepartmentTimeRequirement #klovn
    department: Medical
    time: 7200
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled
    pocket1: Flare
  storage:
    back:
    - Hypospray
    - MedkitCombatFilled
    - MedkitCombatFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled
    pocket1: Flare
  storage:
    back:
    - Hypospray
    - MedkitCombatFilled
    - MedkitCombatFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine

- type: chameleonOutfit
  id: ERTMedicalChameleonOutfit
  job: ERTMedical
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTMedical
    neck: ClothingNeckStethoscope

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: chameleonOutfit
  id: ERTJanitorChameleonOutfit
  job: ERTJanitor
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTJanitor
    neck: ClothingNeckScarfStripedPurple
    eyes: ClothingEyesGlassesSunglasses
