# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 DrSmugleaf
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-FileCopyrightText: 2020 Hugo Laloge
# SPDX-FileCopyrightText: 2020 VÃ­ctor Aguilera Puerto
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2020 scuffedjays
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2022 Emisse
# SPDX-FileCopyrightText: 2022 Ephememory
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2022 keronshb
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Slava0135
# SPDX-FileCopyrightText: 2023 lapatison
# SPDX-FileCopyrightText: 2023 lzk228
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Tayrtahn
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2025 DeusMaldPr
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2025 slarticodefast
#
# SPDX-License-Identifier: MPL-2.0

- type: job
  id: Clown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: JobClown
  requirements:
  - !type:RoleTimeRequirement
    role: JobPassenger
    time: 220 #klovn, 220
  startingGear: ClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
      catchingFailDamage:
        types:
          Blunt: 1
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ClownGear
  equipment:
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: ClownPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampClown
    - CrayonRainbow

- type: chameleonOutfit
  id: ClownChameleonOutfit
  job: Clown
  equipment:
    head: ClothingHeadHatXmasCrown
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingHeadHatFlowerWreath
    outerClothing: ClothingOuterClownPriest
    gloves: ClothingHandsGlovesColorYellowBudget
