# SPDX-FileCopyrightText: 2021 Alex Evgrashin
# SPDX-FileCopyrightText: 2021 Leon Friedrich
# SPDX-FileCopyrightText: 2021 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2022 Fishfish458
# SPDX-FileCopyrightText: 2022 Flipp Syder
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Kevin Zheng
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 ZeroDayDaemon
# SPDX-FileCopyrightText: 2022 Zymem
# SPDX-FileCopyrightText: 2022 fishfish458
# SPDX-FileCopyrightText: 2022 mirrorcult
# SPDX-FileCopyrightText: 2022 theashtronaut
# SPDX-FileCopyrightText: 2023 Alekshhh
# SPDX-FileCopyrightText: 2023 DerbyX
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 Jackal298
# SPDX-FileCopyrightText: 2023 Lei Yunxing
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2023 Topy
# SPDX-FileCopyrightText: 2023 lapatison
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2023 nikthechampiongr
# SPDX-FileCopyrightText: 2024 Hanz
# SPDX-FileCopyrightText: 2024 Ubaser
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2024 Джексон Миссиссиппи
# SPDX-FileCopyrightText: 2025 Gerkada
# SPDX-FileCopyrightText: 2025 Hitlinemoss
# SPDX-FileCopyrightText: 2025 Killerqu00
# SPDX-FileCopyrightText: 2025 ScarKy0
# SPDX-FileCopyrightText: 2025 Tiniest Shark
# SPDX-FileCopyrightText: 2025 Velcroboy
# SPDX-FileCopyrightText: 2025 github_actions[bot]
# SPDX-FileCopyrightText: 2025 iaada
# SPDX-FileCopyrightText: 2025 pathetic meowmeow
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: LockerBoozeFilled
  suffix: Filled
  parent: LockerBooze
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBooze

- type: entityTable
  id: FillLockerBooze
  table: !type:AllSelector
    children:
    - id: ClothingOuterArmorBasicSlim
    - id: WeaponShotgunDoubleBarreledRubber
    - id: DrinkShaker
    - id: ClothingEyesHudBeer
    - id: HandLabeler
    - id: WeaponRussianRevolver # Goobstation
    - id: DrinkBeerBottleFull
      amount: !type:BinomialNumberSelector
        trials: 3
    - !type:AllSelector
      rolls: 2
      children:
      - id: BoxBeanbag
      - id: RagItem

#- type: entity
#  id: LockerFormalFilled
#  suffix: Filled
#  parent: LockerFormal

- type: entity
  id: ClosetChefFilled
  suffix: Filled
  parent: ClosetChef
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetChef

- type: entityTable
  id: FillClosetChef
  table: !type:AllSelector
    children:
    - id: VariantCubeBox
    - id: SprayBottleWater
    - id: FoodBoxCloth
    - id: ReagentContainerSugar
    - id: FoodCondimentBottleEnzyme
    - id: DrinkSoyMilkCarton
    - !type:AllSelector
      rolls: 2
      children:
      - id: DrinkMilkCarton
      # really, milk should go in the fridge. Unfortunately saltern only has freezers.
      # yes, I'm using this as an excuse to not have to do extra work.
      - id: ReagentContainerFlour
      - id: BoxMousetrap
    - !type:AllSelector
      rolls: 3
      children:
      - id: FoodCondimentPacketSalt
      - id: FoodCondimentPacketPepper

- type: entity
  id: ClosetJanitorFilled
  suffix: Filled
  parent: ClosetJanitor
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetJanitor

- type: entityTable
  id: FillClosetJanitor
  table: !type:AllSelector
    children:
    - id: WetFloorSign
      amount: 3
    - id: LightReplacer
    - id: BoxLightMixed
    - id: Holoprojector
    - !type:AllSelector
      rolls: 2
      children:
      - id: MopItem
      - id: BoxMousetrap
      - id: TrashBag
      - id: SoapNT
      - id: FlashlightLantern
      - id: Plunger
      - id: WireBrush

- type: entity
  id: ClosetLegalFilled
  suffix: Filled
  parent: ClosetLegal
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetLegal

- type: entityTable
  id: FillClosetLegal
  table: !type:AllSelector
    children:
    - id: BriefcaseBrownFilled
      prob: 0.80
    - id: ClothingOuterRobesJudge

- type: entity
  id: LockerBotanistFilled
  suffix: Filled
  parent: LockerBotanist
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBotanist

- type: entityTable
  id: FillLockerBotanist
  table: !type:AllSelector
    children:
    - id: ClothingHandsGlovesLeather
    - id: ClothingOuterApronBotanist
    - id: ClothingHeadBandBotany
    - id: ChemistryBottleRobustHarvest
      prob: 0.3
    - id: ClothingBeltPlant
    - id: PlantBag ##Some maps don't have nutrivend
    - id: BoxMouthSwab
    - id: Dropper
    - id: HandLabeler
    - id: ClothingUniformOveralls
    - id: ClothingHeadHatTrucker
      prob: 0.1

- type: entity
  id: LockerBotanistLoot
  suffix: Loot
  parent: LockerBotanist
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBotanistLoot

- type: entityTable
  id: FillLockerBotanistLoot
  table: !type:AllSelector
    children:
    - id: ClothingUniformOveralls
    - id: ClothingHeadHatTrucker
      prob: 0.3
    - id: GatfruitSeeds
      prob: 0.1
    - id: FlyAmanitaSeeds
      prob: 0.5
    - id: NettleSeeds
      prob: 0.7

- type: entity
  id: ClosetJanitorBombFilled
  parent: ClosetJanitorBomb
  suffix: DO NOT MAP, Filled
  categories: [ DoNotMap ]
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetJanitorBomb

- type: entityTable
  id: FillClosetJanitorBomb
  table: !type:AllSelector
    children:
    - id: ClothingHeadHelmetJanitorBombSuit
    - id: ClothingOuterSuitJanitorBomb
